version: '3' 
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /root/nginx-for-kubecost/kubecost/html:/usr/share/nginx/html
      - /root/nginx-for-kubecost/kubecost/nginx.conf:/etc/nginx/nginx.conf
      - /root/nginx-for-kubecost/kubecost/conf.d:/etc/nginx/conf.d
      - /root/nginx-for-kubecost/key:/usr/share/nginx/ssl
